pipeline:
  name: artifact-uploading-test
  registry: https://hub.docker.com/
  image: python:3.9-slim
  upload-repo: https://github.com/CS6510-SEA-SP25/t2-cicd
  stages:
    - build
    - generate-json-files
    - validate
  jobs:
    - name: build-files
      stage: build
      script:
        - "mkdir -p artifacts"
        - 'echo "Hello, World" > artifacts/hello_build.txt'
        - 'echo "Pipeline Artifact Test" > artifacts/info_build_2.txt'
        - "date > timestamp_build.txt"
        - "python3 -c 'import json; json.dump({\"name\": \"artifact1\", \"version\": 1}, open(\"artifacts/artifact1.json\", \"w\"))'"
        - "python3 -c 'import json; json.dump({\"name\": \"artifact2\", \"version\": 2}, open(\"artifacts/artifact2.json\", \"w\"))'"
        - "python3 -c 'import json; json.dump({\"name\": \"timestamp\", \"time\": \"$(date)\"}, open(\"artifacts/timestamp.json\", \"w\"))'"
      artifacts:
        - artifacts/*.txt

    - name: json
      stage: generate-json-files
      script:
        - "mkdir -p artifacts"
        - "python3 -c 'import json; json.dump({\"name\": \"artifact1\", \"version\": 1}, open(\"artifacts/artifact1_2.json\", \"w\"))'"
        - "python3 -c 'import json; json.dump({\"name\": \"artifact2\", \"version\": 2}, open(\"artifacts/artifact2_2.json\", \"w\"))'"
        - "python3 -c 'import json; json.dump({\"name\": \"timestamp\", \"time\": \"$(date)\"}, open(\"artifacts/timestamp_2.json\", \"w\"))'"
      artifacts:
        - artifacts/*.json

    - name: validate-files
      stage: validate
      script:
        - "mkdir -p artifacts"
        - 'echo "Hello, World" > artifacts/hello_validate.txt'
        - 'echo "Pipeline Artifact Test" > artifacts/info_validate.txt'
        - "date > timestamp_validate_2.txt"
