pipeline:
  name: "no-stage-pipeline"
  stages:

  jobs:
    - name: "build-job"
      stage: "build"
      image: "node:16"
      script:
        - "npm install"
        - "npm run build"
    - name: "test-job"
      stage: "test"
      image: "node:16"
      script:
        - "npm test"
      needs:
        - "build-job"

    - name: "docs-job"
      stage: "doc"
      image: "node:16"
      script:
        - "npm run docs"
      needs:
        - "test-job"

    - name: "deploy-job"
      stage: "deploy"
      image: "node:16"
      script:
        - "npm run deploy"
      needs:
        - "docs-job"
