pipeline:
  name: test-artifact-uploading
  registry: https://hub.docker.com/
  image: python:3.9-slim
  upload-repo: https://github.com/CS6510-SEA-SP25/t2-cicd
  stages:
    - build
  jobs:
    - name: generate-image-files
      stage: build
      script:
        - "mkdir -p artifacts"
        # Images
        - "pip install pillow"
        - "python3 -c 'from PIL import Image; img = Image.new(\"RGB\", (60, 30), color = \"red\"); img.save(\"artifacts/red_image.png\")'"
        - "python3 -c 'from PIL import Image; img = Image.new(\"RGB\", (60, 30), color = \"blue\"); img.save(\"artifacts/blue_image.png\")'"
        - "python3 -c 'from PIL import Image; img = Image.new(\"RGB\", (60, 30), color = \"green\"); img.save(\"artifacts/green_image.png\")'"

        # JSON
        - "python3 -c 'import json; json.dump({\"name\": \"artifact1\", \"version\": 1}, open(\"artifacts/artifact1.json\", \"w\"))'"
        - "python3 -c 'import json; json.dump({\"name\": \"artifact2\", \"version\": 2}, open(\"artifacts/artifact2.json\", \"w\"))'"
        - "python3 -c 'import json; json.dump({\"name\": \"timestamp\", \"time\": \"$(date)\"}, open(\"artifacts/timestamp.json\", \"w\"))'"
        
        # TXT
        - 'echo "Hello, World" > artifacts/hello.txt'
        - 'echo "Pipeline Artifact Test" > artifacts/info.txt'
        - "date > artifacts/timestamp.txt"
      artifacts:
        - artifacts/info.txt
        - artifacts/*.json