mongodb:
  #    uri: mongodb://host.docker.internal:27017/team_2
  uri: mongodb://mongodb:27017/team_2
  database: team_2
  collection: pipeline_runs
minio:
  url: http://minio:9000
  username: admin
  password: password123
rabbitmq:
  host: rabbitmq
#  host: localhost
