services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - pipeline-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - pipeline-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    networks:
      - pipeline-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  docker-socket-proxy:
    image: alpine/socat
    container_name: docker-socket-proxy
    command: TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
    ports:
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pipeline-network
    restart: unless-stopped

  server:
    container_name: server
    build:
      context: team2-server-app
    environment:
      PROJECT_DIR: ${PWD}/team2-server-app/local_artifacts 
    depends_on:
      mongodb:
        condition: service_healthy
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      docker-socket-proxy:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./team2-cli-app/.pipelines:/app/.pipelines
      - ./team2-server-app/local_artifacts:/app/local_artifacts
    networks:
      - pipeline-network
    privileged: true
    restart: always

  worker:
    container_name: worker
    build:
      context: team2-worker-app
    environment:
      PROJECT_DIR: ${PWD}/team2-worker-app/local_artifacts
    depends_on:
      mongodb:
        condition: service_healthy
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./team2-worker-app/local_artifacts:/app/local_artifacts
    networks:
      - pipeline-network
    privileged: true
    restart: always

networks:
  pipeline-network:
    driver: bridge

volumes:
  mongodb-data:
    name: mongodb-data
    driver: local
  minio-data:
    name: minio-data
    driver: local
  rabbitmq-data:
    name: rabbitmq-data
    driver: local