services:
  server:
    image: server
    build:
      context: .
    environment:
      PROJECT_DIR: ${PWD}/local_artifacts
    depends_on:
      mongodb:
        condition: service_healthy
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      docker-socket-proxy:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../team2-cli-app/.pipelines:/app/.pipelines
      - ./local_artifacts:/app/local_artifacts
    networks:
      - server-network
    privileged: true
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - server-network
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5


  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - server-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - server-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  docker-socket-proxy:
    image: alpine/socat
    container_name: docker-socket-proxy
    command: TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
    ports:
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - server-network
    restart: unless-stopped


networks:
  server-network:
    driver: bridge

volumes:
  mongodb-data:
    name: mongodb-data
    driver: local
  minio-data:
    name: minio-data
    driver: local
  rabbitmq-data:
    name: rabbitmq-data
    driver: local