apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: pipeline-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: yashvigarg/worker:latest
        env:
        - name: PROJECT_DIR
          value: /app/local_artifacts
        volumeMounts:
        - name: worker-data
          mountPath: /app/local_artifacts
      volumes:
      - name: worker-data
        emptyDir: {}
