pipeline:
  name: "duplicate-name-pipeline"
  stages:
    - build
    - test
    - docs

  jobs:
    - name: "build-job"
      stage: "build"
      image: "node:16"
      script:
        - "npm install"
        - "npm run build"

    - name: "build-job"
      stage: "test"
      image: "node:16"
      script:
        - "npm test"
      needs:
        - "build-job"

    - name: "docs-job"
      stage: "docs"
      image: "node:16"
      script:
        - "npm run docs"
      needs:
        - "test-job"
