pipeline:
  name: "failure-pipeline"
  stages:
    - build
    - test
    - deploy
  jobs:
    - name: "build-job"
      stage: "build"
      image: "node:16"
      script:
        - "echo 'Starting build...'"
        - "echo 'Build failed' && exit 1"  # This will fail

    - name: "test-job"
      stage: "test"
      image: "node:16"
      script:
        - "echo 'Running tests...'"  # Should never execute
      needs:
        - "build-job"

    - name: "deploy-job"
      stage: "deploy"
      image: "node:16"
      script:
        - "echo 'Deploying...'"  # Should never execute
      needs:
        - "test-job"